### ISSUE TITLE
NEVPNIKEAuthenticationMethodNone problem

### ISSUE THREAD

**Issue by linKnowEasy** [zqqf16/IKEv2_Demo#3]
你好, 谢谢你的开源项目
 我在学习过程中, 碰到一个问题, 能麻烦你看一下么？
使用 NEVPNProtocolIKEv2 VPN 链接的时候. 
 startVPNTunnelAndReturnError 调用成功之后 
VPN 状态 NEVPNStatusConnecting -> NEVPNStatusDisconnecting ->NEVPNStatusDisconnected

而直接使用系统创建的 VPN , VPN 链接就是正常的

VPN 服务器用的CA 证书, 这是我的配置代码
`

            NEVPNProtocolIKEv2 *protocol = [[NEVPNProtocolIKEv2 alloc] init];
            protocol.serverAddress = vpnInfo.serverAddress;
            protocol.remoteIdentifier = vpnInfo.remoteID;
            protocol.username = vpnInfo.username;            
            // 设置密码
            static NSString *passwordKey = @"k_VPN_Password";
            [self setKeychainWithString:vpnInfo.password forIdentifier:passwordKey];
            protocol.passwordReference = [self   getDataReferenceInKeychainFromIdentifier:passwordKey];
            protocol.authenticationMethod = NEVPNIKEAuthenticationMethodNone;
            protocol.useExtendedAuthentication = YES;
            protocol.disconnectOnSleep = NO;

            _vpnManager.protocolConfiguration = protocol;
            _vpnManager.onDemandEnabled = YES;
            _vpnManager.localizedDescription = vpnInfo.preferenceTitle;
            _vpnManager.enabled = YES;
`
如能抽空查看, 不胜感激

**Comment by zqqf16** [comment]
不好意思哈，很久没看这部分代码，记不太清了。感觉 
`protocol.authenticationMethod = NEVPNIKEAuthenticationMethodNone; `
可能又问题，试过其他的认证方式了么？

另外，可以配合一下手机 console log，以及 VPN server log 来排查一下

**Comment by linKnowEasy** [comment]
还是感谢您的回复。
我参考了 https://forums.developer.apple.com/thread/77374 这个链接

目前怀疑是 SA 过程中出问题了, 说是系统创建的 SA 会自动做处理, 代码创建的,需要手动设置。

但是 NEVPNProtocolIKEv2 的 SA 相关属性  `IKESecurityAssociationParameters` ` childSecurityAssociationParameters`都是 readonly 

目前在寻找调整 SA 的办法.
如果后续如果解决了, 我会补充在这里

**Comment by linKnowEasy** [comment]
通过调整 
`
            protocol.IKESecurityAssociationParameters.encryptionAlgorithm = XX;
            protocol.childSecurityAssociationParameters.encryptionAlgorithm = XX;
`
SA 属性, 已经成功了, 如果发生类似, 链接后立刻断开, 可以与服务端 日志结合, 排查一下 SA 。 
再次感谢 @zqqf16  开源 demo 的帮助

**Comment by redsun** [comment]
@linKnowEasy 能不能具体说一下这两个值该如何设置，我服务器的日志是这个
May 10 03:00:33 vultr charon: 15[CFG] received proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA1/MODP_1024
May 10 03:00:33 vultr charon: 15[CFG] configured proposals: IKE:AES_CBC_128/AES_CBC_192/AES_CBC_256/CAMELLIA_CBC_128/CAMELLIA_CBC_192/CAMELLIA_CBC_256/3DES_CBC/HMAC_SHA2_256_128/HMAC_SHA2_384_192/HMAC_SHA2_512_256/HMAC_SHA1_96/AES_XCBC_96/AES_CMAC_96/PRF_HMAC_SHA2_256/PRF_HMAC_SHA2_384/PRF_HMAC_SHA2_512/PRF_AES128_XCBC/PRF_AES128_CMAC/PRF_HMAC_SHA1/ECP_256/ECP_384/ECP_521/ECP_256_BP/ECP_384_BP/ECP_512_BP/CURVE_25519/MODP_3072/MODP_4096/MODP_6144/MODP_8192/MODP_2048, IKE:AES_GCM_16_128/AES_GCM_16_192/AES_GCM_16_256/AES_GCM_12_128/AES_GCM_12_192/AES_GCM_12_256/AES_GCM_8_128/AES_GCM_8_192/AES_GCM_8_256/PRF_HMAC_SHA2_256/PRF_HMAC_SHA2_384/PRF_HMAC_SHA2_512/PRF_AES128_XCBC/PRF_AES128_CMAC/PRF_HMAC_SHA1/ECP_256/ECP_384/ECP_521/ECP_256_BP/ECP_384_BP/ECP_512_BP/CURVE_25519/MODP_3072/MODP_4096/MODP_6144/MODP_8192/MODP_2048

**Comment by linKnowEasy** [comment]
@redsun  iOS 系统支持的SA 
![image](https://user-images.githubusercontent.com/8413135/39850745-a482226a-5445-11e8-91d0-0c817e036d0d.png)

如果你不清楚服务端支持哪些, 可以一个一个试过去。

不过一般  algorithmAES128  algorithmAES256 会偏多

**Comment by redsun** [comment]
@linKnowEasy 感谢解答，
protocol.IKESecurityAssociationParameters.encryptionAlgorithm = XX; protocol.childSecurityAssociationParameters.encryptionAlgorithm = XX;

我一个一个试了  protocol.IKESecurityAssociationParameters.encryptionAlgorithm = XX; ，没有尝试第二个，childSecurityAssociationParameters  这个要和 IKESecurityAssociationParameters. 保持一致吗？

**Comment by linKnowEasy** [comment]
@redsun  得看服务端的配置. 一般情况的话. 这两个会配置成一样的. 如果服务端配置成不一样的话.建议你找一下服务端同学 问下SA

**Comment by redsun** [comment]
@linKnowEasy 你配置过吗，这个是我自己搭建的，搜的配置，电脑 或者手机都可以链接，唯独用代码链接不上，和你的情况一样，我在研究研究，感谢解答。

**Comment by linKnowEasy** [comment]
@redsun  不好意思,我自己没有配置过, 给不了这方面的帮助。
